### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by neallred** [bcbooks/scriptures-json#4]
Would you have any interest in distributing the JSON output files in this repository as an NPM package? That would make it easier to pull the JSON into JS-based projects. I know the output files do not change a lot, but when they do, it would be handy to pull in a later version via NPM/Yarn rather than re-copying the files into repos that use it.

**Comment by bencrowder** [comment]
@neallred Great idea! I'll get on it.

**Comment by bencrowder** [comment]
@neallred Here you go: https://www.npmjs.com/package/@bencrowder/scriptures-json

(For some reason, the website isn't showing the README no matter what I do.)

**Comment by neallred** [comment]
Awesome, thank you so much!!
