### ISSUE TITLE
Remove npm dependency in latest published version

### ISSUE THREAD

**Issue by neallred** [bcbooks/scriptures-json#5]
Thanks again for publishing this to NPM! It's been super helpful in some personal projects.

One thing I noticed is `npm` is [still included as a dependency]( https://www.npmjs.com/package/@bencrowder/scriptures-json) even though it was removed from the [package.json](https://github.com/bcbooks/scriptures-json/commit/dce335f069e248d46275e3dc3761e05021c5c29b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Maybe a version bump and a republish would fix the issue?

**Comment by bencrowder** [comment]
Oops, sorry about that. (It didn't make it to the package-lock.json, which I think was the issue.) It's fixed in version 1.0.1: https://www.npmjs.com/package/@bencrowder/scriptures-json
