### ISSUE TITLE
implemented python access

### ISSUE THREAD

**Issue by jer-magland** [bcbooks/scriptures-json#6]
Hi @bencrowder, thanks for sharing all these files!

I made this package for Python access to the books/chapters/verses/words of the Book of Mormon text: https://github.com/jer-magland/bookofmormon

Let me know if you want me to cite your work differently, or if you want me to integrate differently. For now I just copied your .json file into my repo so it can be distributed right along with the package.

**Comment by bencrowder** [comment]
You're fine. Since it's public domain, you can cite or not however you want, really. (I'm not particular about it.) But it's nice to see how it's being used, so thanks for letting me know!

**Comment by jer-magland** [comment]
@bencrowder A follow-up, also created a typescript interface, and I am making this website with your data: https://www.bookofmormontext.org
